### ISSUE TITLE
Vulkan: support for erupt

### ISSUE THREAD

**Issue by Vincent-P** [Traverse-Research/gpu-allocator#108]
It would be great to support https://gitlab.com/Friz64/erupt.

**Comment by UditDey** [comment]
I think the solution followed by [gpu-alloc](https://crates.io/crates/gpu-alloc) is good. They have separate `gpu-alloc-<backend>` crates for working with different vulkan wrappers or even `gfx-hal`. The hard dependency on `ash` is the only thing keeping me from using this crate at the moment.

**Comment by MarijnS95** [comment]
https://github.com/ash-rs/ash/issues/344#issuecomment-1122827964 / https://gitlab.com/Friz64/erupt/-/issues/56: We (the `ash` maintainers and author of `erupt`) are working towards housing the strength of both crates under one roof, effectively bringing `erupt`s improved generator and some API changes to `ash`. There will be only one crate going forward.

After all, a low-level Vulkan wrapper should have little enough divergence from the API it's wrapping to warrant multiple "competing" doing the same thing.

**Comment by UditDey** [comment]
That's good to hear, looking forward to moving to the new wrapper. In the meantime, I'm making a fork of this crate to work with `erupt`.
