### ISSUE TITLE
Configurable allocation size

### ISSUE THREAD

**Issue by Elabajaba** [Traverse-Research/gpu-allocator#156]
Currently it seems like gpu-allocator allocated a 256MB buffer on the gpu every time you initialize it. `wgpu` isn't only used for games, so it'd be nice if we could configure the block size to be smaller for eg. apps like [wezterm](https://github.com/wez/wezterm.git).

**Comment by i509VCB** [comment]
This would also be nice for the Vulkan renderer I am writing for Smithay.
