### ISSUE TITLE
Support _unreleased_ breaking API changes from Ash `master` branch

### ISSUE THREAD

**Issue by codecnotsupported** [Traverse-Research/gpu-allocator#166]
https://github.com/ash-rs/ash/pull/602/commits/845e1dcb609ce93e7d67103fddb6e56a43b4d964

https://github.com/search?q=repo%3ATraverse-Research%2Fgpu-allocator+Info%3A%3Abuilder%28%29&type=code
So maybe bump the version and replace `Info::builder()` with `Info::default()`?

**Comment by MarijnS95** [comment]
Those breaking changes only live in the `master` branch of Ash and have not made it to a published _semver-breaking_ release yet. Will close this as there's nothing actionable for `gpu-allocator` until an official release (on crates.io) is available.

If you need access to new features of `ash` (such as more recent Vulkan API symbols/wrappers), chances are I've picked them to the backwards-compatible [`0.37-stable` branch](https://github.com/ash-rs/ash/tree/0.37-stable) which can be used in `[patch.crates-io]` to replace `ash` globally in your own crate _and `gpu-allocator`_.

That said I am slowly working towards making the next breaking release of Ash happen, now that all the worries around having too many _semver-breaking_ Ash releases in quick succession have cooled down. However, just after we had many slow months, Ash is suddenly picking up a large influx of **necessary** breaking changes to fix incorrect API wrappers and broken function loaders, so we might take some more time to ensure everything makes it in prior to publishing this release.

When that happens I'll update crates like `gpu-allocator` in advance to feel out the latest release and make extra sure it's ready for prime-time.

**Comment by MarijnS95** [comment]
@codecnotsupported I've just pushed a preliminary bump to to `ash`'s `master` branch at https://github.com/Traverse-Research/gpu-allocator/compare/ash-0.38, to start testing the new API across a wider range of crates, which you can use if you wish to consume `ash` from its git `master` branch.

As said before though there are more **breaking** changes to be made to fix longstanding issues and regressions, meaning an `ash 0.38` release isn't very close yet.

**Comment by codecnotsupported** [comment]
Awesome, thanks.
