### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by cwfitzgerald** [Traverse-Research/gpu-allocator#170]
Quite a few things (including `windows-rs` version bumps) have landed that would be great to get into a release, would it be possible to get a new release?

**Comment by MarijnS95** [comment]
0.23 got released last week :tada: 

https://github.com/Traverse-Research/gpu-allocator/commit/ab75548220d906c5ec6c66a81155a7b6f4f614e5

https://github.com/Traverse-Research/gpu-allocator/releases/tag/0.23.0

**Comment by cwfitzgerald** [comment]
Woot!
