### ISSUE TITLE
Attempting to allocate a large chunk of `CpuToGpu` memory will result in a validation warning.

### ISSUE THREAD

**Issue by max-traverse** [Traverse-Research/gpu-allocator#57]
When attempting to allocate a large (> 256MiB) chunk of `CpuToGpu` memory, it will try to allocate to `DEVICE_LOCAL | HOST_VISIBLE | DEVICE_COHERENT` memory first.  The heap of that type of memory is usually fairly small ( <= 256 MiB). Attempting to allocate here results in a validation warning. `gpu-allocator` already correctly attempts to allocate from another memory type if it's available. However, we should test the heap size before attempting to allocate to avoid this warning.

**Comment by MarijnS95** [comment]
Fixed in #60!
