### ISSUE TITLE
Switch over to windows-rs

### ISSUE THREAD

**Issue by Jasper-Bekkers** [Traverse-Research/gpu-allocator#62]
Right now we're still reliant on the legacy `winapi` crate that's slowly being replaced with `windows-rs`, we'll need to do the same for our DirectX support.

**Comment by MarijnS95** [comment]
We've already converted our public API to (by default) not expose any specific windows implementations and accept `c_void` pointers instead. Head-start made in the examples to show easy compatibility: https://github.com/Traverse-Research/gpu-allocator/pull/47 - and we can do the same on the internal side of things to have a cleaner, more convenient and safer API :)
