### ISSUE TITLE
A way to change the debug name of existing allocations

### ISSUE THREAD

**Issue by expenses** [Traverse-Research/gpu-allocator#66]
This might be a tall order given how the code is laid out, but it'd be really nice to be able to rename allocations for when a buffer is re-used for a different purpose. One example would be a buffer that's first used for initialization but then is cloned and used as a per-frame resource for double-buffering. Ideally in that case you'd copy the buffer once and rename the original.

Simply change the `Allocation::name` field won't work, you'd also need to change the `MemoryChunk::name` field so that the new name is used for leak-detection.

**Comment by max-traverse** [comment]
I think some sort of `allocator.rename_allocation(&mut my_allocation);` function should be possible. If we make this part of the allocator we have all the information required to rename it in the whole system.

**Comment by max-traverse** [comment]
Would something like this cover your use case? https://github.com/Traverse-Research/gpu-allocator/pull/67

**Comment by expenses** [comment]
@max-traverse Yep, that works perfectly!! 🎉

**Comment by max-traverse** [comment]
I have merged the feature in :tada:
