### ISSUE TITLE
Validation layer error `VUID-vkMapMemory-memory-00683: Memory ... must not have been allocated with multiple instances` when attempting to allocate vertex buffers

### ISSUE THREAD

**Issue by Zeno343** [Traverse-Research/gpu-allocator#71]
When trying to allocate a CpuToGpu vertex buffer I get the following validation layer error, accompanied by debug logs:

```
2021-09-27 08:10:28,141 DEBUG [winit::platform_impl::platform::x11::window] Calculated physical dimensions: 1920x1080
2021-09-27 08:10:28,224 DEBUG [gpu_allocator::vulkan] memory type count: 4
2021-09-27 08:10:28,224 DEBUG [gpu_allocator::vulkan] memory heap count: 3
2021-09-27 08:10:28,224 DEBUG [gpu_allocator::vulkan] memory type[0]: prop flags: 0x1, heap[0]
2021-09-27 08:10:28,224 DEBUG [gpu_allocator::vulkan] memory type[1]: prop flags: 0x6, heap[1]
2021-09-27 08:10:28,224 DEBUG [gpu_allocator::vulkan] memory type[2]: prop flags: 0x7, heap[2]
2021-09-27 08:10:28,224 DEBUG [gpu_allocator::vulkan] memory type[3]: prop flags: 0xe, heap[1]
2021-09-27 08:10:28,224 DEBUG [gpu_allocator::vulkan] heap[0] flags: 0x3, size: 3840 MiB
2021-09-27 08:10:28,224 DEBUG [gpu_allocator::vulkan] heap[1] flags: 0x0, size: 4096 MiB
2021-09-27 08:10:28,224 DEBUG [gpu_allocator::vulkan] heap[2] flags: 0x3, size: 256 MiB
2021-09-27 08:10:28,986 DEBUG [gpu_allocator::vulkan] Allocating `mesh` of 36 bytes with an alignment of 4.
VUID-vkMapMemory-memory-00683(ERROR / SPEC): msgNum: -1067763043 - Validation Error: [ VUID-vkMapMemory-memory-00683 ] Object 0: handle = 0x2e2941000000001f, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0xc05b3a9d | Memory (VkDeviceMemory 0x2e2941000000001f[]) must not have been allocated with multiple instances -- either by supplying a deviceMask with more than one bit set, or by allocation from a heap with the MULTI_INSTANCE heap flag set. The Vulkan spec states: memory must not have been allocated with multiple instances (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkMapMemory-memory-00683)
    Objects: 1
        [0] 0x2e2941000000001f, type: 8, name: NULL
2021-09-27 08:10:30,941 DEBUG [gpu_allocator::vulkan] Freeing `mesh`.
```

**Comment by max-traverse** [comment]
Hi! Thank you for reporting this issue.
It looks like this is a multi-gpu issue. Could you share your setup with us?
We haven't done any testing with multi-gpu setups so far, but we can look into making `gpu-allocator`  compatible with those.

**Comment by Zeno343** [comment]
I'm getting this on a single Radeon 580. I don't even have integrated graphics on my CPU, so it should be just the one GPU as far as I can tell.

**Comment by Zeno343** [comment]
I did some digging and vulkaninfo reports the following about the device memory, if that helps:

VkPhysicalDeviceMemoryProperties:
=================================
memoryHeaps: count = 3
	memoryHeaps[0]:
		size   = 4026531840 (0xf0000000) (3.75 GiB)
		budget = 3825205504 (0xe4000100) (3.56 GiB)
		usage  = 0 (0x00000000) (0.00 B)
		flags: count = 2
			MEMORY_HEAP_DEVICE_LOCAL_BIT
			MEMORY_HEAP_MULTI_INSTANCE_BIT
	memoryHeaps[1]:
		size   = 4294967296 (0x100000000) (4.00 GiB)
		budget = 4080218880 (0xf3333300) (3.80 GiB)
		usage  = 0 (0x00000000) (0.00 B)
		flags:
			None
	memoryHeaps[2]:
		size   = 268435456 (0x10000000) (256.00 MiB)
		budget = 255013680 (0x0f333330) (243.20 MiB)
		usage  = 0 (0x00000000) (0.00 B)
		flags: count = 2
			MEMORY_HEAP_DEVICE_LOCAL_BIT
			MEMORY_HEAP_MULTI_INSTANCE_BIT
memoryTypes: count = 4
	memoryTypes[0]:
		heapIndex     = 0
		propertyFlags = 0x0001: count = 1
			MEMORY_PROPERTY_DEVICE_LOCAL_BIT
		usable for:
			IMAGE_TILING_OPTIMAL:
				color images
				FORMAT_D16_UNORM
				FORMAT_D32_SFLOAT
				FORMAT_S8_UINT
				FORMAT_D16_UNORM_S8_UINT
				FORMAT_D32_SFLOAT_S8_UINT
			IMAGE_TILING_LINEAR:
				color images
	memoryTypes[1]:
		heapIndex     = 1
		propertyFlags = 0x0006: count = 2
			MEMORY_PROPERTY_HOST_VISIBLE_BIT
			MEMORY_PROPERTY_HOST_COHERENT_BIT
		usable for:
			IMAGE_TILING_OPTIMAL:
				color images
				FORMAT_D16_UNORM
				FORMAT_D32_SFLOAT
				FORMAT_S8_UINT
				FORMAT_D16_UNORM_S8_UINT
				FORMAT_D32_SFLOAT_S8_UINT
			IMAGE_TILING_LINEAR:
				color images
	memoryTypes[2]:
		heapIndex     = 2
		propertyFlags = 0x0007: count = 3
			MEMORY_PROPERTY_DEVICE_LOCAL_BIT
			MEMORY_PROPERTY_HOST_VISIBLE_BIT
			MEMORY_PROPERTY_HOST_COHERENT_BIT
		usable for:
			IMAGE_TILING_OPTIMAL:
				color images
				FORMAT_D16_UNORM
				FORMAT_D32_SFLOAT
				FORMAT_S8_UINT
				FORMAT_D16_UNORM_S8_UINT
				FORMAT_D32_SFLOAT_S8_UINT
			IMAGE_TILING_LINEAR:
				color images
	memoryTypes[3]:
		heapIndex     = 1
		propertyFlags = 0x000e: count = 3
			MEMORY_PROPERTY_HOST_VISIBLE_BIT
			MEMORY_PROPERTY_HOST_COHERENT_BIT
			MEMORY_PROPERTY_HOST_CACHED_BIT
		usable for:
			IMAGE_TILING_OPTIMAL:
				color images
				FORMAT_D16_UNORM
				FORMAT_D32_SFLOAT
				FORMAT_S8_UINT
				FORMAT_D16_UNORM_S8_UINT
				FORMAT_D32_SFLOAT_S8_UINT
			IMAGE_TILING_LINEAR:
				color images

**Comment by max-traverse** [comment]
That's interesting since we have tested with an RX 570 before. I'll try to find some time soon to look into this more closely!

**Comment by MarijnS95** [comment]
@Zeno343 Can you repost that memoryinfo? It's where the problem lies and truly interesting to us!

> winit::platform_impl::platform::x11::window

Looks like you're on Linux. What driver are you using? RADV or AMDVLK or AMDGPU-PRO?

**Comment by Zeno343** [comment]
Yup, I only deleted it because I forgot you can edit comments and I'm terrible at markdown :D
'''
VkPhysicalDeviceMemoryProperties:
=================================
memoryHeaps: count = 3
	memoryHeaps[0]:
		size   = 4026531840 (0xf0000000) (3.75 GiB)
		budget = 3825205504 (0xe4000100) (3.56 GiB)
		usage  = 0 (0x00000000) (0.00 B)
		flags: count = 2
			MEMORY_HEAP_DEVICE_LOCAL_BIT
			MEMORY_HEAP_MULTI_INSTANCE_BIT
	memoryHeaps[1]:
		size   = 4294967296 (0x100000000) (4.00 GiB)
		budget = 4080218880 (0xf3333300) (3.80 GiB)
		usage  = 0 (0x00000000) (0.00 B)
		flags:
			None
	memoryHeaps[2]:
		size   = 268435456 (0x10000000) (256.00 MiB)
		budget = 255013680 (0x0f333330) (243.20 MiB)
		usage  = 0 (0x00000000) (0.00 B)
		flags: count = 2
			MEMORY_HEAP_DEVICE_LOCAL_BIT
			MEMORY_HEAP_MULTI_INSTANCE_BIT
memoryTypes: count = 4
	memoryTypes[0]:
		heapIndex     = 0
		propertyFlags = 0x0001: count = 1
			MEMORY_PROPERTY_DEVICE_LOCAL_BIT
		usable for:
			IMAGE_TILING_OPTIMAL:
				color images
				FORMAT_D16_UNORM
				FORMAT_D32_SFLOAT
				FORMAT_S8_UINT
				FORMAT_D16_UNORM_S8_UINT
				FORMAT_D32_SFLOAT_S8_UINT
			IMAGE_TILING_LINEAR:
				color images
	memoryTypes[1]:
		heapIndex     = 1
		propertyFlags = 0x0006: count = 2
			MEMORY_PROPERTY_HOST_VISIBLE_BIT
			MEMORY_PROPERTY_HOST_COHERENT_BIT
		usable for:
			IMAGE_TILING_OPTIMAL:
				color images
				FORMAT_D16_UNORM
				FORMAT_D32_SFLOAT
				FORMAT_S8_UINT
				FORMAT_D16_UNORM_S8_UINT
				FORMAT_D32_SFLOAT_S8_UINT
			IMAGE_TILING_LINEAR:
				color images
	memoryTypes[2]:
		heapIndex     = 2
		propertyFlags = 0x0007: count = 3
			MEMORY_PROPERTY_DEVICE_LOCAL_BIT
			MEMORY_PROPERTY_HOST_VISIBLE_BIT
			MEMORY_PROPERTY_HOST_COHERENT_BIT
		usable for:
			IMAGE_TILING_OPTIMAL:
				color images
				FORMAT_D16_UNORM
				FORMAT_D32_SFLOAT
				FORMAT_S8_UINT
				FORMAT_D16_UNORM_S8_UINT
				FORMAT_D32_SFLOAT_S8_UINT
			IMAGE_TILING_LINEAR:
				color images
	memoryTypes[3]:
		heapIndex     = 1
		propertyFlags = 0x000e: count = 3
			MEMORY_PROPERTY_HOST_VISIBLE_BIT
			MEMORY_PROPERTY_HOST_COHERENT_BIT
			MEMORY_PROPERTY_HOST_CACHED_BIT
		usable for:
			IMAGE_TILING_OPTIMAL:
				color images
				FORMAT_D16_UNORM
				FORMAT_D32_SFLOAT
				FORMAT_S8_UINT
				FORMAT_D16_UNORM_S8_UINT
				FORMAT_D32_SFLOAT_S8_UINT
			IMAGE_TILING_LINEAR:
				color images
'''

I'm using the amdvlk driver from the Arch repository

**Comment by Zeno343** [comment]
I switched to the RADV driver and the validation complaint went away, for what that's worth. Looks like it's the open source flavor of AMDVLK that was causing trouble.

**Comment by MarijnS95** [comment]
@Zeno343 Thanks for confirming! We'll take it from here and see what's up with AMDVLK :)

**Comment by Jasper-Bekkers** [comment]
This appears to potentially be a validation layer bug, we're following up with Khronos.

**Comment by Tobski** [comment]
I've just filed https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3350 for this.

**Comment by Jasper-Bekkers** [comment]
Fixed in the validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3351
